name: Helm package creation

on:
  workflow_dispatch:

env:
    REGISTRY: ghcr.io
    # github.repository as <account>/<repo>
    PACKAGE_NAME: ${{ github.repository }}

jobs:
  release-helm-artifacte:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Login to Helm registry
        run: |
          helm registry login ${{ env.REGISTRY }} --username ${{ github.actor }} --password ${{ secrets.GH_TOKEN }}

      - name: save Helm package to local registry
        run: |
          helm chart save ${{ github.workspace }}/deployment/ ${{ env.REGISTRY }}/${{ env.PACKAGE_NAME }}:${{ github.sha }}

      - name: Upload Helm package to remote registry
        run: |
          helm registry login ${{ env.REGISTRY }} --username ${{ github.actor }} --password ${{ secrets.GH_TOKEN }}
          